source 'http://rubygems.org'

gem 'rdf'
gem 'rdf-rdfxml'
gem 'rdf-trig'
gem 'nokogiri'
gem 'rake'
gem 'rest-client'
gem 'json'
gem 'rspec'
gem 'rspec-mocks'
gem 'autotest', '~> 4.4.6'
gem 'autotest-growl'
gem 'hub'
